---@meta _

--[[
SKILL 相关常量用于 Skill.GetData
]]
CONST.SKILL_ID = 0;
CONST.SKILL_COMMENT = 1;
CONST.SKILL_WHICHASSORT = 2;
CONST.SKILL_DEFAULTMAXLEVEL = 3;
CONST.SKILL_EXPTABLE = 4;
CONST.SKILL_COST = 5;
CONST.SKILL_DIFFICULTY = 6;
CONST.SKILL_NEEDEQUIP = 7;
CONST.SKILL_S_TABLE = 8;
CONST.SKILL_REQUIRESLOT = 9;
CONST.SKILL_OPERATION = 10;
CONST.SKILL_RATIOPOPULATION = 11;
CONST.SKILL_GETSTAMINA = 12;
CONST.SKILL_GETDEX = 13;
CONST.SKILL_GETINTELLIGENCE = 14;
CONST.SKILL_EXPFLG = 15;
CONST.SKILL_JOBS = 16;
CONST.SKILL_RATE = 17;
CONST.SKILL_NAME = 4000;

--[[
TECH 相关常量用于 Tech.GetData
]]
CONST.TECH_ID = 0;
CONST.TECH_AREA_USE = 0;
CONST.TECH_COMMENT = 1;
CONST.TECH_AREA_ENABLE = 1;
CONST.TECH_SKILLID = 2;
CONST.TECH_AREA_ID = 2;
CONST.TECH_NECESSARYLV = 3;
CONST.TECH_AREA_SKILLID = 3;
CONST.TECH_FIELD = 4;
CONST.TECH_AREA_CFGID = 4;
CONST.TECH_TARGET = 5;
CONST.TECH_AREA_SEQNO = 5;
CONST.TECH_COST = 6;
CONST.TECH_AREA_MAPID = 6;
CONST.TECH_DRESSAGE = 7;
CONST.TECH_AREA_FLOOR = 7;
CONST.TECH_FORCEPOINT = 8;
CONST.TECH_AREA_FROMX = 8;
CONST.TECH_REMAIN = 9;
CONST.TECH_AREA_FROMY = 9;
CONST.TECH_REMEMBER_RECIPE1 = 10;
CONST.TECH_AREA_TOX = 10;
CONST.TECH_REMEMBER_RECIPE2 = 11;
CONST.TECH_AREA_TOY = 11;
CONST.TECH_AREA_ZORDER = 12;
CONST.TECH_AREA_FAILEDPROB = 13;
CONST.TECH_AREA_ITEMID1 = 14;
CONST.TECH_AREA_ITEMID2 = 15;
CONST.TECH_AREA_ITEMID3 = 16;
CONST.TECH_AREA_ITEMID4 = 17;
CONST.TECH_AREA_ITEMID5 = 18;
CONST.TECH_AREA_ITEMID6 = 19;
CONST.TECH_AREA_ITEMID7 = 20;
CONST.TECH_AREA_ITEMID8 = 21;
CONST.TECH_AREA_ITEMID9 = 22;
CONST.TECH_AREA_ITEMID10 = 23;
CONST.TECH_AREA_ITEMPROB1 = 24;
CONST.TECH_AREA_ITEMPROB2 = 25;
CONST.TECH_AREA_ITEMPROB3 = 26;
CONST.TECH_AREA_ITEMPROB4 = 27;
CONST.TECH_AREA_ITEMPROB5 = 28;
CONST.TECH_AREA_ITEMPROB6 = 29;
CONST.TECH_AREA_ITEMPROB7 = 30;
CONST.TECH_AREA_ITEMPROB8 = 31;
CONST.TECH_AREA_ITEMPROB9 = 32;
CONST.TECH_AREA_ITEMPROB10 = 33;
CONST.TECH_AREA_NEED_ITEM = 34;
CONST.TECH_NAME = 4000;
CONST.TECH_AREA_NAME = 4000;
CONST.TECH_FUNCNAME = 4001;
CONST.TECH_OPTION = 4002;


--[[
ITEMSET 相关常量用于 Item.GetData 或 Data.ItemsetGetData
]]
CONST.ITEMSET_ID = 0 --物品ID;
CONST.ITEMSET_BASEIMAGENUMBER = 1 --图档ID;
CONST.ITEMSET_COST = 2 --价格;
CONST.ITEMSET_TYPE = 3 --类型;
CONST.ITEMSET_OTHERFLG = 4 --其他标志;
CONST.ITEMSET_EQUIPBOTHHAND = 5 --双手装备;
CONST.ITEMSET_ABLEUSEFIELD = 6 --可双击;
CONST.ITEMSET_ABLEUSEBATTLE = 7 --战斗可用;
CONST.ITEMSET_TARGET = 8 --战斗使用目标;
CONST.ITEMSET_REMAIN = 9 --最小采集数;
CONST.ITEMSET_MAXREMAIN = 10 --最大堆叠数;
CONST.ITEMSET_LEVEL = 11 --等级;
CONST.ITEMSET_BASEFAILEDPROB = 12 --基础失败率（目测无用）;
CONST.ITEMSET_MAXDURABILITY = 13 --最小耐久;
CONST.ITEMSET_ATTACKNUM_MIN = 14 --最小攻击次数;
CONST.ITEMSET_ATTACKNUM_MAX = 15 --最大攻击次数;
CONST.ITEMSET_ABLEEFFECTBETWEENHAVE = 16 --无需装备加能力;
CONST.ITEMSET_MODIFYMODFLG = 17 --百分比装备;
CONST.ITEMSET_MODIFYATTACK = 18 --最小攻击;
CONST.ITEMSET_MODIFYDEFENCE = 19 --最小防御;
CONST.ITEMSET_MODIFYAGILITY = 20 --最小敏捷;
CONST.ITEMSET_MODIFYMAGIC = 21 --最小精神;
CONST.ITEMSET_MODIFYRECOVERY = 22 --最小回复;
CONST.ITEMSET_MODIFYCRITICAL = 23 --最小必杀;
CONST.ITEMSET_MODIFYCOUNTER = 24 --最小反击;
CONST.ITEMSET_MODIFYHITRATE = 25 --最小命中;
CONST.ITEMSET_MODIFYAVOID = 26 --最小闪躲;
CONST.ITEMSET_MODIFYHP = 27 --最小生命;
CONST.ITEMSET_MODIFYFORCEPOINT = 28 --最小魔力;
CONST.ITEMSET_MODIFYLUCK = 29 --最小幸运;
CONST.ITEMSET_MODIFYCHARISMA = 30 --最小魅力（目测无用）;
CONST.ITEMSET_MODIFYCHARM = 31 --最小魅力值;
CONST.ITEMSET_MODIFYATTRIB = 32 --水晶属性1;
CONST.ITEMSET_MODIFYATTRIB2 = 33 --水晶属性2;
CONST.ITEMSET_MODIFYATTRIBVALUE = 34 --水晶属性1值;
CONST.ITEMSET_MODIFYATTRIBVALUE2 = 35 --水晶属性2值;
CONST.ITEMSET_MODIFYSTAMINA = 36 --最小耐力;
CONST.ITEMSET_MODIFYDEX = 37 --最小灵巧;
CONST.ITEMSET_MODIFYINTELLIGENCE = 38 --最小智力;
CONST.ITEMSET_POISON = 39 --最小抗毒;
CONST.ITEMSET_SLEEP = 40 --最小抗睡;
CONST.ITEMSET_STONE = 41 --最小抗石;
CONST.ITEMSET_DRUNK = 42 --最小抗醉;
CONST.ITEMSET_CONFUSION = 43 --最小抗乱;
CONST.ITEMSET_AMNESIA = 44 --最小抗忘;
CONST.ITEMSET_SPECIALEFFECT = 45 --特殊功能;
CONST.ITEMSET_SPECIALEFFECTVALUE = 46 --功能参数1;
CONST.ITEMSET_SPECIALEFFECTVALUE2 = 47 --功能参数2;
CONST.ITEMSET_MATERIAL_WEAPON = 48 --宝石_武器;
CONST.ITEMSET_MATERIAL_ARMOUR = 49 --宝石_防具;
CONST.ITEMSET_MATERIAL_ACCESSORY = 50 --宝石_饰品;
CONST.ITEMSET_USEACTION = 51 --使用动作（目测无用）;
CONST.ITEMSET_DROPATLOGOUT = 52 --登出消失;
CONST.ITEMSET_VANISHATDROP = 53 --丢出消失;
CONST.ITEMSET_CANPETMAIL = 54 --可交易邮件;
CONST.ITEMSET_RSS = 55 --最小魔抗;
CONST.ITEMSET_CANSELL = 56 --可出售;
CONST.ITEMSET_EXPLANATION1 = 57 --物品说明;
CONST.ITEMSET_EXPLANATION2 = 58 --右键说明;
CONST.ITEMSET_LEAKEDPROB = 59 --鉴定概率;
CONST.ITEMSET_RARE_FLG = 60 --黑白宝箱能否开出;
CONST.ITEMSET_INBOX_FLG = 61 --普通宝箱能否开出;
CONST.ITEMSET_PUTTIME = 62 --放置时间;
CONST.ITEMSET_LEAKLEVEL = 63 --鉴定等级（目测无用）;
CONST.ITEMSET_MERGEFLG = 64 --能否合成（珊瑚工具之前有，目测无用）;
CONST.ITEMSET_DURABILITY = 65 --耐久度（目测无用）;
CONST.ITEMSET_SELLUNIT = 66 --是否可出售;
CONST.ITEMSET_CREATETIME = 67 --创建时间;
CONST.ITEMSET_TIMELIMIT = 68 --限时有效期;
CONST.ITEMSET_ENDTIME = 69 --到期时间;
CONST.ITEMSET_VAR1 = 70 --变量1;
CONST.ITEMSET_VAR2 = 71 --变量2;
CONST.ITEMSET_VAR3 = 72 --变量3;
CONST.ITEMSET_VAR4 = 73 --变量4;
CONST.ITEMSET_ADM = 74 --最小魔攻;
CONST.ITEMSET_HOUSE_X = 75 --房屋_X;
CONST.ITEMSET_HOUSE_Y = 76 --房屋_Y;
CONST.ITEMSET_MONSTERATTRIB = 77 --怪物种族（目测无用）;
CONST.ITEMSET_WEIGHT = 78 --最小负重;
CONST.ITEMSET_FIRSTNAME = 4000 --未鉴定名;
CONST.ITEMSET_TRUENAME = 4001 --道具名称;
CONST.ITEMSET_MEMO = 4002 --刻印;
CONST.ITEMSET_ARGUMENT = 4003 --使用效果;
CONST.ITEMSET_RENAMECDKEY = 4004 --刻印玩家;
CONST.ITEMSET_INITFUNC = 4005 --道具定义;
CONST.ITEMSET_WATCHFUNC = 4006 --观察函数;
CONST.ITEMSET_USEFUNC = 4007 --道具功能;
CONST.ITEMSET_ATTACHFUNC = 4008 --装备函数;
CONST.ITEMSET_DETACHFUNC = 4009 --卸下函数;
CONST.ITEMSET_DROPFUNC = 4010 --丢弃函数;
CONST.ITEMSET_PREPICKUPFUNC = 4011 --拾取前函数;
CONST.ITEMSET_PICKUPFUNC = 4012 --拾取函数;
CONST.ITEMSET_MAXHIT = 88 --最大采集数;
CONST.ITEMSET_MAXITEMDURABILITY = 92 --最大耐久;
CONST.ITEMSET_MAXMODIFYATTACK = 97 --最大攻击;
CONST.ITEMSET_MAXMODIFYDEFENCE = 98 --最大防御;
CONST.ITEMSET_MAXMODIFYAGILITY = 99 --最大敏捷;
CONST.ITEMSET_MAXMODIFYMAGIC = 100 --最大精神;
CONST.ITEMSET_MAXMODIFYRECOVERY = 101 --最大回复;
CONST.ITEMSET_MAXMODIFYCRITICAL = 102 --最大必杀;
CONST.ITEMSET_MAXMODIFYCOUNTER = 103 --最大反击;
CONST.ITEMSET_MAXMODIFYHITRATE = 104 --最大命中;
CONST.ITEMSET_MAXMODIFYAVOID = 105 --最大闪躲;
CONST.ITEMSET_MAXMODIFYHP = 106 --最大生命;
CONST.ITEMSET_MAXMODIFYFORCEPOINT = 107 --最大魔力;
CONST.ITEMSET_MAXMODIFYLUCK = 108 --最大幸运;
CONST.ITEMSET_MAXMODIFYCHARM = 110 --最大魅力值;
CONST.ITEMSET_MAXMODIFYSTAMINA = 115 --最大耐力;
CONST.ITEMSET_MAXMODIFYDEX = 116 --最大灵巧;
CONST.ITEMSET_MAXMODIFYINTELLIGENCE = 117 --最大智力;
CONST.ITEMSET_MAXPOISON = 118 --最大抗毒;
CONST.ITEMSET_MAXSLEEP = 119 --最大抗睡;
CONST.ITEMSET_MAXSTONE = 120 --最大抗石;
CONST.ITEMSET_MAXDRUNK = 121 --最大抗醉;
CONST.ITEMSET_MAXCONFUSION = 122 --最大抗乱;
CONST.ITEMSET_MAXAMNESIA = 123 --最大抗忘;
CONST.ITEMSET_MAXRSS = 134 --最大魔抗;
CONST.ITEMSET_MAXADM = 153 --最大魔攻;
CONST.ITEMSET_MAXWEIGHT = 157 --最大负重;


--[[
ENCOUNT 相关常量用于 Data.GetEncountData
]]
CONST.ENCOUNT_USE = 0;
CONST.ENCOUNT_GROUP_ID = 0;
CONST.ENCOUNT_INDEX = 1;
CONST.ENCOUNT_GROUP_APPEARBYITEMID = 1;
CONST.ENCOUNT_SEQNO = 2;
CONST.ENCOUNT_GROUP_NOTAPPEARBYITEMID = 2;
CONST.ENCOUNT_MAPID = 3;
CONST.ENCOUNT_GROUP_ENEMY_ID1 = 3;
CONST.ENCOUNT_FLOOR = 4;
CONST.ENCOUNT_GROUP_ENEMY_ID2 = 4;
CONST.ENCOUNT_ENCOUNTPROB_MIN = 5;
CONST.ENCOUNT_GROUP_ENEMY_ID3 = 5;
CONST.ENCOUNT_ENCOUNTPROB_MAX = 6;
CONST.ENCOUNT_GROUP_ENEMY_ID4 = 6;
CONST.ENCOUNT_ENEMYMAXNUM = 7;
CONST.ENCOUNT_GROUP_ENEMY_ID5 = 7;
CONST.ENCOUNT_ZORDER = 8;
CONST.ENCOUNT_GROUP_ENEMY_ID6 = 8;
CONST.ENCOUNT_NEXTENCOUNTID = 9;
CONST.ENCOUNT_GROUP_ENEMY_ID7 = 9;
CONST.ENCOUNT_NEXTENCOUNTPROB = 10;
CONST.ENCOUNT_GROUP_ENEMY_ID8 = 10;
CONST.ENCOUNT_ENEMYLEVEL = 11;
CONST.ENCOUNT_GROUP_ENEMY_ID9 = 11;
CONST.ENCOUNT_RANDRANGE = 12;
CONST.ENCOUNT_GROUP_ENEMY_ID10 = 12;
CONST.ENCOUNT_GROUPID1 = 13;
CONST.ENCOUNT_GROUP_CREATEPROB1 = 13;
CONST.ENCOUNT_GROUPID2 = 14;
CONST.ENCOUNT_GROUP_CREATEPROB2 = 14;
CONST.ENCOUNT_GROUPID3 = 15;
CONST.ENCOUNT_GROUP_CREATEPROB3 = 15;
CONST.ENCOUNT_GROUPID4 = 16;
CONST.ENCOUNT_GROUP_CREATEPROB4 = 16;
CONST.ENCOUNT_GROUPID5 = 17;
CONST.ENCOUNT_GROUP_CREATEPROB5 = 17;
CONST.ENCOUNT_GROUPID6 = 18;
CONST.ENCOUNT_GROUP_CREATEPROB6 = 18;
CONST.ENCOUNT_GROUPID7 = 19;
CONST.ENCOUNT_GROUP_CREATEPROB7 = 19;
CONST.ENCOUNT_GROUPID8 = 20;
CONST.ENCOUNT_GROUP_CREATEPROB8 = 20;
CONST.ENCOUNT_GROUPID9 = 21;
CONST.ENCOUNT_GROUP_CREATEPROB9 = 21;
CONST.ENCOUNT_GROUPID10 = 22;
CONST.ENCOUNT_GROUP_CREATEPROB10 = 22;
CONST.ENCOUNT_CREATEPROB1 = 23;
CONST.ENCOUNT_GROUP_ABSOLUTE1 = 23;
CONST.ENCOUNT_CREATEPROB2 = 24;
CONST.ENCOUNT_GROUP_ABSOLUTE2 = 24;
CONST.ENCOUNT_GROUP_ABSOLUTE3 = 25;
CONST.ENCOUNT_CREATEPROB3 = 25;
CONST.ENCOUNT_GROUP_ABSOLUTE4 = 26;
CONST.ENCOUNT_CREATEPROB4 = 26;
CONST.ENCOUNT_GROUP_ABSOLUTE5 = 27;
CONST.ENCOUNT_CREATEPROB5 = 27;
CONST.ENCOUNT_GROUP_ABSOLUTE6 = 28;
CONST.ENCOUNT_CREATEPROB6 = 28;
CONST.ENCOUNT_GROUP_ABSOLUTE7 = 29;
CONST.ENCOUNT_CREATEPROB7 = 29;
CONST.ENCOUNT_GROUP_ABSOLUTE8 = 30;
CONST.ENCOUNT_CREATEPROB8 = 30;
CONST.ENCOUNT_GROUP_ABSOLUTE9 = 31;
CONST.ENCOUNT_CREATEPROB9 = 31;
CONST.ENCOUNT_GROUP_ABSOLUTE10 = 32;
CONST.ENCOUNT_CREATEPROB10 = 32;
CONST.ENCOUNT_X = 33;
CONST.ENCOUNT_Y = 34;
CONST.ENCOUNT_WIDTH = 35;
CONST.ENCOUNT_HEIGHT = 36;
CONST.ENCOUNT_GROUP_NAME = 4000;
CONST.ENCOUNT_GROUP_FORMATION = 4001;

--- 背包总页数
CONST.EXTBAGPAGE = 0;

--- 全局最大道具栏
CONST.EXTITEMMAX = 28;

--[[
方向常量
]]
CONST.左上 = 0;
CONST.上 = 1;
CONST.右上 = 2;
CONST.右 = 3;
CONST.右下 = 4;
CONST.下 = 5;
CONST.左下 = 6;
CONST.左 = 7;

CONST.ENDEVENT1 = 85;
CONST.ENDEVENT2 = 86;
CONST.ENDEVENT3 = 87;
CONST.ENDEVENT4 = 88;
CONST.ENDEVENT5 = 89;
CONST.ENDEVENT6 = 90;
CONST.ENDEVENT7 = 91;
CONST.ENDEVENT8 = 92;
CONST.NOWEVENT1 = 117;
CONST.NOWEVENT2 = 118;
CONST.NOWEVENT3 = 119;
CONST.NOWEVENT4 = 120;
CONST.NOWEVENT5 = 121;
CONST.NOWEVENT6 = 122;
CONST.NOWEVENT7 = 123;
CONST.NOWEVENT8 = 124;
CONST.RECIPE1 = 149;
CONST.RECIPE2 = 150;
CONST.RECIPE3 = 151;
CONST.RECIPE4 = 152;
CONST.RECIPE5 = 153;
CONST.RECIPE6 = 154;
CONST.RECIPE7 = 155;
CONST.RECIPE8 = 156;
CONST.RECIPE9 = 157;
CONST.RECIPE10 = 158;
CONST.RECIPE11 = 159;
CONST.RECIPE12 = 160;
CONST.RECIPE13 = 161;
CONST.RECIPE14 = 162;
CONST.RECIPE15 = 163;
CONST.RECIPE16 = 164;
CONST.RECIPE17 = 165;
CONST.RECIPE18 = 166;
CONST.RECIPE19 = 167;
CONST.RECIPE20 = 168;
CONST.RECIPE21 = 169;
CONST.RECIPE22 = 170;
CONST.RECIPE23 = 171;
CONST.RECIPE24 = 172;
CONST.RECIPE25 = 173;
CONST.RECIPE26 = 174;
CONST.RECIPE27 = 175;
CONST.RECIPE28 = 176;
CONST.RECIPE29 = 177;
CONST.RECIPE30 = 178;
CONST.RECIPE31 = 179;
CONST.RECIPE32 = 180;
CONST.ALBUM1 = 213;
CONST.ALBUM2 = 214;
CONST.ALBUM3 = 215;
CONST.ALBUM4 = 216;
CONST.ALBUM5 = 217;
CONST.ALBUM6 = 218;
CONST.ALBUM7 = 219;
CONST.ALBUM8 = 220;
CONST.ALBUM9 = 221;
CONST.ALBUM10 = 222;
CONST.ALBUM11 = 223;
CONST.ALBUM12 = 224;
CONST.ALBUM13 = 225;
CONST.ALBUM14 = 226;
CONST.ALBUM15 = 227;
CONST.ALBUM16 = 228;
CONST.ALBUM17 = 229;
CONST.ALBUM18 = 230;
CONST.ALBUM19 = 231;
CONST.ALBUM20 = 232;
CONST.ALBUM21 = 233;
CONST.ALBUM22 = 234;
CONST.ALBUM23 = 235;
CONST.ALBUM24 = 236;
CONST.ALBUM25 = 237;
CONST.ALBUM26 = 238;
CONST.ALBUM27 = 239;
CONST.ALBUM28 = 240;
CONST.ALBUM29 = 241;
CONST.ALBUM30 = 242;
CONST.ALBUM31 = 243;
CONST.ALBUM32 = 244;
CONST.LASTSAVETIME = 251;
CONST.RANKDOWNFLG = 252;
CONST.PENALTY = 256;
CONST.TIMEOUTDUNGEONID = 262;
CONST.TIMEOUTSERVERNUMBER = 263;

--[[
ITEM_RECIPE 用于  Recipe.GetData
]]
CONST.ITEM_RECIPE_ID = 0;
CONST.ITEM_RECIPE_ITEMID = 1;
CONST.ITEM_OTHERFLG_INCUSE = 1;
CONST.ITEM_RECIPE_SKILLID = 2;
CONST.ITEM_OTHERFLG_HANKO = 2;
CONST.ITEM_RECIPE_EXP = 3;
CONST.ITEM_RECIPE_A = 4;
CONST.ITEM_OTHERFLG_SHOVEL = 4;
CONST.ITEM_RECIPE_B = 5;
CONST.ITEM_RECIPE_C = 6;
CONST.ITEM_RECIPE_D = 7;
CONST.ITEM_RECIPE_E = 8;
CONST.ITEM_OTHERFLG_CANADDJEWEL = 8;
CONST.ITEM_RECIPE_REQUIRE_A = 9;
CONST.ITEM_RECIPE_REQUIRE_B = 10;
CONST.ITEM_RECIPE_REQUIRE_C = 11;
CONST.ITEM_RECIPE_REQUIRE_D = 12;
CONST.ITEM_RECIPE_REQUIRE_E = 13;
CONST.ITEM_OTHERFLG_IMMUTABLE = 16;
CONST.ITEM_OTHERFLG_UNBREAK = 32;
CONST.ITEM_RECIPE_NAME = 4000;
CONST.ITEM_OTHERFLG_DISABLE = 1073741824;

--[[
窗口类型
]]
CONST.窗口_信息框 = 0;
CONST.窗口_输入框 = 1;
CONST.窗口_选择框 = 2;
CONST.窗口_宠物选择框 = 3;
CONST.窗口_组队选择框 = 4;
CONST.窗口_买卖框 = 5;
CONST.窗口_买框 = 6;
CONST.窗口_商店买 = 6;
CONST.窗口_卖框 = 7;
CONST.窗口_商店卖 = 7;
CONST.窗口_巨信息框 = 10;
CONST.窗口_巨输入框 = 11;
CONST.窗口_图框 = 37;

--[[
NPC_EVENT_TYPE 用于 CONST.对象_NPC_EVENT_TYPE 解析
]]
CONST.NPC_EVENT_TYPE_NONE = 0;
CONST.NPC_EVENT_TYPE_NPC = 1;
CONST.NPC_EVENT_TYPE_ENEMY = 2;
CONST.NPC_EVENT_TYPE_WARP = 3;
CONST.NPC_EVENT_TYPE_WARP_OBJECT = 10;

--[[
战斗类型
]]
CONST.战斗_普通 = 1;
CONST.战斗_PVP = 2;
CONST.战斗_观战 = 3;
CONST.战斗_BOSS战 = 5;

--[[
战斗奖励类型
]]
CONST.战奖_普通 = 0;
CONST.战奖_PVP = 1;

--[[
宠物成长档类型
]]
CONST.宠档_体成 = 1;
CONST.宠档_力成 = 2;
CONST.宠档_强成 = 3;
CONST.宠档_敏成 = 4;
CONST.宠档_魔成 = 5;

CONST.颜色_白色 = 0;
CONST.颜色_青色 = 1;
CONST.颜色_紫色 = 2;
CONST.颜色_蓝色 = 3;
CONST.颜色_黄色 = 4;
CONST.颜色_绿色 = 5;
CONST.颜色_红色 = 6;
CONST.颜色_灰色 = 7;
CONST.颜色_灰蓝色 = 8;
CONST.颜色_灰绿色 = 9;

CONST.字体_中 = 0;
CONST.字体_小 = 1;
CONST.字体_大 = 2;

--[[
对象的动作类型 用于 NLG.SetAction
]]
CONST.动作_站立 = 0;
CONST.动作_走路 = 1;
CONST.动作_跑步 = 3;
CONST.动作_攻击 = 5;
CONST.动作_魔法 = 6;
CONST.动作_投掷 = 7;
CONST.动作_受伤 = 8;
CONST.动作_防御 = 9;
CONST.动作_倒下 = 10;
CONST.动作_坐下 = 11;
CONST.动作_招手 = 12;
CONST.动作_高兴 = 13;
CONST.动作_生气 = 14;
CONST.动作_悲伤 = 15;
CONST.动作_点头 = 16;
CONST.动作_石头 = 17;
CONST.动作_剪刀 = 18;
CONST.动作_布 = 19;

CONST.战属_攻吸 = 0;
CONST.战属_攻反 = 1;
CONST.战属_攻无 = 2;
CONST.战属_魔吸 = 3;
CONST.战属_魔反 = 4;
CONST.战属_魔无 = 5;
CONST.战属_毒 = 6;
CONST.战属_睡 = 7;
CONST.战属_石 = 8;
CONST.战属_醉 = 9;
CONST.战属_忘 = 10;
CONST.战属_乱 = 11;
CONST.战属_防增 = 12;
CONST.战属_攻增 = 13;
CONST.战属_敏增 = 14;
CONST.战属_恢增 = 15;
CONST.战属_恢复魔法 = 16;
CONST.战属_恢复回合 = 17;
CONST.战属_属转 = 18;
CONST.战属_慢舞回合 = 19;
CONST.战属_慢舞值 = 20;
CONST.战属_舞回合 = 21;
CONST.战属_等回合 = 22;
CONST.战属_参数 = 23;


--[[
玩家道具栏位
]]
CONST.道栏_头位 = 0;
CONST.道栏_身位 = 1;
CONST.道栏_左手 = 2;
CONST.道栏_右手 = 3;
CONST.道栏_脚位 = 4;
CONST.道栏_首饰1 = 5;
CONST.道栏_首饰2 = 6;
CONST.道栏_水晶 = 7;
CONST.道栏_1 = 8;
CONST.道栏_2 = 9;
CONST.道栏_3 = 10;
CONST.道栏_4 = 11;
CONST.道栏_5 = 12;
CONST.道栏_6 = 13;
CONST.道栏_7 = 14;
CONST.道栏_8 = 15;
CONST.道栏_9 = 16;
CONST.道栏_10 = 17;
CONST.道栏_11 = 18;
CONST.道栏_12 = 19;
CONST.道栏_13 = 20;
CONST.道栏_14 = 21;
CONST.道栏_15 = 22;
CONST.道栏_16 = 23;
CONST.道栏_17 = 24;
CONST.道栏_18 = 25;
CONST.道栏_19 = 26;
CONST.道栏_20 = 27;

--[[
宠物道具栏位
]]
CONST.宠道栏_水晶 = 0;
CONST.宠道栏_身体 = 1;
CONST.宠道栏_颈圈 = 2;
CONST.宠道栏_饰品1 = 3;
CONST.宠道栏_饰品2 = 4;

--[[
玩家宠物栏位
]]
CONST.宠物栏_1 = 0;
CONST.宠物栏_2 = 1;
CONST.宠物栏_3 = 1;
CONST.宠物栏_4 = 3;
CONST.宠物栏_5 = 4;

--[[
队伍栏位
]]
CONST.队员_队长 = 0;
CONST.队员_1 = 1;
CONST.队员_2 = 2;
CONST.队员_3 = 3;
CONST.队员_4 = 4;

--[[
道具类型
]]
CONST.道具类型_剑 = 0;
CONST.道具类型_斧 = 1;
CONST.道具类型_枪 = 2;
CONST.道具类型_杖 = 3;
CONST.道具类型_弓 = 4;
CONST.道具类型_小刀 = 5;
CONST.道具类型_回力镖 = 6;
CONST.道具类型_盾 = 7;
CONST.道具类型_盔 = 8;
CONST.道具类型_帽 = 9;
CONST.道具类型_铠 = 10;
CONST.道具类型_衣 = 11;
CONST.道具类型_袍 = 12;
CONST.道具类型_靴 = 13;
CONST.道具类型_鞋 = 14;
CONST.道具类型_手环 = 15;
CONST.道具类型_乐器 = 16;
CONST.道具类型_项链 = 17;
CONST.道具类型_戒指 = 18;
CONST.道具类型_头带 = 19;
CONST.道具类型_耳环 = 20;
CONST.道具类型_护身符 = 21;
CONST.道具类型_水晶 = 22;
CONST.道具类型_料理 = 23;
CONST.道具类型_家具 = 24;
CONST.道具类型_果皮 = 25;
CONST.道具类型_不明 = 26;
CONST.道具类型_宝箱 = 27;
CONST.道具类型_钥匙 = 28;
CONST.道具类型_矿石 = 29;
CONST.道具类型_木材 = 30;
CONST.道具类型_布卷 = 31;
CONST.道具类型_肉类 = 32;
CONST.道具类型_海鲜 = 33;
CONST.道具类型_蔬菜 = 34;
CONST.道具类型_其他食材 = 35;
CONST.道具类型_香草 = 36;
CONST.道具类型_药草 = 37;
CONST.道具类型_宝石 = 38;
CONST.道具类型_B类材料 = 39;
CONST.道具类型_封印卡 = 40;
CONST.道具类型_其他卡片 = 41;
CONST.道具类型_点心 = 42;
CONST.道具类型_药品 = 43;
CONST.道具类型_书籍 = 44;
CONST.道具类型_地图 = 45;
CONST.道具类型_飞行 = 46;
CONST.道具类型_彩票 = 47;
CONST.道具类型_其他 = 48;
CONST.道具类型_邮票 = 48;
CONST.道具类型_改造材料 = 49;
CONST.道具类型_图鉴 = 50;
CONST.道具类型_炸药 = 51;
CONST.道具类型_粪便 = 52;
CONST.道具类型_小吃 = 53;
CONST.道具类型_各种 = 54;
CONST.道具类型_头饰 = 55;
CONST.道具类型_宠物水晶 = 56;
CONST.道具类型_宠物饰品 = 57;
CONST.道具类型_宠物装甲 = 58;
CONST.道具类型_宠物服饰 = 59;
CONST.道具类型_宠物颈圈 = 60;
CONST.道具类型_宠物护符 = 61;

--[[
对象属性，含玩家、NPC、宠物、怪物, 用于Char.GetData
]]
CONST.对象_类型 = 3;
CONST.对象_序 = 3;
CONST.对象_形象 = 4;
CONST.对象_可视 = 4;
CONST.对象_原形 = 5;
CONST.对象_地图类型 = 6;
CONST.对象_MAP = 6;
CONST.对象_地图 = 7;
CONST.对象_X = 8;
CONST.对象_Y = 9;
CONST.对象_方向 = 10;
CONST.对象_等级 = 11;
CONST.对象_血 = 12;
CONST.对象_魔 = 13;
CONST.对象_体力 = 14;
CONST.对象_力量 = 15;
CONST.对象_强度 = 16;
CONST.对象_速度 = 17;
CONST.对象_魔法 = 18;
CONST.对象_运 = 19;
CONST.对象_运气 = 19;
CONST.对象_种族 = 20;
CONST.对象_地属性 = 21;
CONST.对象_水属性 = 22;
CONST.对象_火属性 = 23;
CONST.对象_风属性 = 24;
CONST.对象_抗毒 = 25;
CONST.对象_抗睡 = 26;
CONST.对象_抗石 = 27;
CONST.对象_抗醉 = 28;
CONST.对象_抗乱 = 29;
CONST.对象_抗忘 = 30;
CONST.对象_必杀 = 31;
CONST.对象_反击 = 32;
CONST.对象_命中 = 33;
CONST.对象_闪躲 = 34;
CONST.对象_道具栏 = 35;
CONST.对象_技能栏 = 36;
CONST.对象_死亡数 = 37;
CONST.对象_伤害数 = 38;
CONST.对象_杀宠数 = 39;
CONST.对象_占卜时间 = 40;
CONST.对象_受伤 = 41;
CONST.对象_移间 = 42;
CONST.对象_循时 = 43;
CONST.对象_经验 = 44;
CONST.对象_升级点 = 45;
CONST.对象_图类 = 46;
CONST.对象_名色 = 47;
CONST.对象_ALLOCPOINT = 48;
CONST.对象_吃时 = 49;
CONST.对象_DataPN = 51;
CONST.对象_RegistNumber = 52;
CONST.对象_职业 = 53;
CONST.对象_职阶 = 54;
CONST.对象_职类ID = 55;
CONST.对象_脸 = 56;
CONST.对象_金币 = 57;
CONST.对象_银行金币 = 58;
CONST.对象_耐力 = 59;
CONST.对象_灵巧 = 60;
CONST.对象_EnemyBaseId = 61;
CONST.对象_智力 = 61;
CONST.对象_魅力 = 62;
CONST.对象_声望 = 63;
CONST.对象_称号 = 64;
CONST.对象_记录点 = 65;
CONST.对象_战宠 = 66;
CONST.对象_聊天距离 = 67;
CONST.对象_HelpPoint = 68;
CONST.对象_登陆次数 = 69;
CONST.对象_说话次数 = 70;
CONST.对象_说次 = 70;
CONST.对象_获得宠数 = 71;
CONST.对象_宠得数 = 71;
CONST.对象_邮数 = 72;
CONST.对象_PET_DepartureBattleStatus = 73;
CONST.对象_生产数 = 73;
CONST.对象_走动次数 = 74;
CONST.对象_走次 = 74;
CONST.对象_宠死亡数 = 75;
CONST.对象_宠死数 = 75;
CONST.对象_宠复活数 = 76;
CONST.对象_宠复数 = 76;
CONST.对象_宠治疗数 = 77;
CONST.对象_宠治数 = 77;
CONST.对象_封印数 = 78;
CONST.对象_OtherFlg = 79;
CONST.对象_日声望上限 = 80;
CONST.对象_声望获取时间 = 81;
CONST.对象_声望下降时间 = 82;
CONST.对象_Renewalflg = 84;
CONST.对象_银行最大宠数 = 245;
CONST.对象_银行最大物数 = 246;
CONST.对象_DP = 247;
CONST.对象_话色 = 248;
CONST.对象_位置 = 249;
CONST.对象_GM = 250;
CONST.对象_掉魂 = 256;
CONST.对象_登陆点 = 257;
CONST.对象_卡时 = 259;
CONST.对象_房子ID = 260;
CONST.对象_房子期限 = 261;
CONST.对象_原始图档 = 264;
CONST.对象_战斗中 = 442;
CONST.对象_战斗状态 = 442;
CONST.对象_BattleIndex = 443;
CONST.对象_战斗Index = 443;
CONST.对象_战斗Side = 444;
CONST.对象_最大血 = 457;
CONST.对象_最大魔 = 458;
CONST.对象_攻击力 = 459;
CONST.对象_防御力 = 460;
CONST.对象_敏捷 = 461;
CONST.对象_精神 = 462;
CONST.对象_回复 = 463;
CONST.对象_DamageAbsrob = 481;
CONST.对象_DamageReflec = 482;
CONST.对象_DamageVanish = 483;
CONST.对象_DamageMagicAbsrob = 484;
CONST.对象_DamageMagicReflec = 485;
CONST.对象_DamageMagicVanish = 486;
CONST.对象_LpRecovery = 487;
CONST.对象_Reverse = 489;
CONST.对象_实际抗毒 = 490;
CONST.对象_Poison = 490;
CONST.对象_实际抗睡 = 491;
CONST.对象_Sleep = 491;
CONST.对象_实际抗石 = 492;
CONST.对象_Stone = 492;
CONST.对象_实际抗醉 = 493;
CONST.对象_Drunk = 493;
CONST.对象_实际抗乱 = 494;
CONST.对象_Confusion = 494;
CONST.对象_实际抗忘 = 495;
CONST.对象_Amnesia = 495;
CONST.对象_ModPoison = 496;
CONST.对象_ModSleep = 497;
CONST.对象_ModStone = 498;
CONST.对象_ModDrunk = 499;
CONST.对象_ModConfusion = 500;
CONST.对象_ModAmnesia = 501;
CONST.对象_实际必杀 = 502;
CONST.对象_实际反击 = 503;
CONST.对象_实际命中 = 504;
CONST.对象_实际闪躲 = 505;
CONST.对象_OBJ = 507;
CONST.对象_获得经验 = 514;
CONST.对象_获得DP = 514;
CONST.对象_移速 = 546;
CONST.对象_ENEMY_PetFlg = 560;
CONST.对象_FD = 560;
CONST.对象_ENEMY_ActionFlag = 561;
CONST.对象_组队模式 = 561;
CONST.对象_NPC_EVENT_TYPE = 562;
CONST.对象_ENEMY_BossFlg = 562;
CONST.对象_最低遇敌率 = 562;
CONST.对象_ENEMY_ModCaptureDefault = 563;
CONST.对象_最高遇敌率 = 563;
CONST.对象_ENEMY_Tactics = 564;
CONST.对象_ENEMY_Summon1 = 565;
CONST.对象_ENEMY_Summon2 = 566;
CONST.对象_NPC_HeadGraNo = 567;
CONST.对象_ENEMY_Escape = 567;
CONST.对象_ENEMY_Msg = 568;
CONST.对象_rideImage = 569;
CONST.对象_ENEMY_BattleAction = 570;
CONST.对象_魔攻 = 573;
CONST.对象_魔法攻击力 = 573;
CONST.对象_魔强 = 573;
CONST.对象_魔抗 = 574;
CONST.对象_魔法防御力 = 574;
CONST.对象_魔法抗性 = 574;
CONST.对象_PET_HeadGraNo = 583;
CONST.对象_ENEMY_ID = 587;
CONST.对象_香下限 = 589;
CONST.对象_香上限 = 590;
CONST.对象_香步数 = 591;
CONST.对象_ENEMY_HeadGraNo = 593;
CONST.对象_ENEMY_STYLE = 594;
CONST.对象_WindowBuffer1 = 594;
CONST.对象_WindowBuffer2 = 595;
CONST.对象_WindowBuffer3 = 596;
CONST.对象_名字 = 4000;
CONST.对象_原名 = 4000;
CONST.对象_玩家称号 = 4001;
CONST.对象_宠名 = 4001;
CONST.对象_CDK = 4002;
CONST.对象_账号 = 4002;
CONST.对象_主人CDK = 4003;
CONST.对象_主人名字 = 4004;
CONST.对象_主人原名 = 4004;
CONST.对象_战死 = 6000;
CONST.对象_战斗信息开关 = 6001;
CONST.对象_登陆富豪榜 = 6002;
CONST.对象_组队开关 = 6003;
CONST.对象_PK开关 = 6004;
CONST.对象_对战开关 = 6004;
CONST.对象_队聊开关 = 6005;
CONST.对象_名片开关 = 6006;
CONST.对象_交易开关 = 6007;
CONST.对象_打卡 = 6008;
CONST.对象_网络超时 = 6009;
CONST.对象_家族开关 = 6010;
CONST.对象_DEBUG开关 = 8000;
CONST.对象_使用MIC = 8001;
CONST.对象_已保存 = 8002;
CONST.对象_不遇敌开关 = 8003;
CONST.对象_自动战斗开关 = 0;
CONST.对象_自动战斗准备状态 = 0;
CONST.对象_原登MAP = 12000;
CONST.对象_原登地图 = 12001;
CONST.对象_原登X = 12002;
CONST.对象_原登Y = 12003;
CONST.对象_RebirthSkill = 0;
CONST.对象_RebirthFlag = 0;
CONST.对象_RebirthView = 0;
CONST.对象_RebirthLevel = 0;
CONST.对象_RebirthAttr = 0;
CONST.对象_RebirthBaseImage = 0;
CONST.对象_骑宠 = 0;

--[[
道具属性 用于 Item.GetData
]]
CONST.道具_序 = 0;
CONST.道具_ID = 0;
CONST.道具_图 = 1;
CONST.道具_价格 = 2;
CONST.道具_类型 = 3;
CONST.道具_OTHERFLG = 4;
CONST.道具_双手 = 5;
CONST.道具_双击 = 6;
CONST.道具_可双击 = 6;
CONST.道具_战斗可用 = 7;
CONST.道具_使用范围 = 8;
CONST.道具_堆叠数 = 9;
CONST.道具_最大堆叠数 = 10;
CONST.道具_等级 = 11;
CONST.道具_最大耐久 = 13;
CONST.道具_最小攻击数量 = 14;
CONST.道具_最大攻击数量 = 15;
CONST.道具_属性类型 = 17;
CONST.道具_攻击 = 18;
CONST.道具_防御 = 19;
CONST.道具_敏捷 = 20;
CONST.道具_精神 = 21;
CONST.道具_回复 = 22;
CONST.道具_必杀 = 23;
CONST.道具_反击 = 24;
CONST.道具_命中 = 25;
CONST.道具_闪躲 = 26;
CONST.道具_生命 = 27;
CONST.道具_HP = 27;
CONST.道具_魔力 = 28;
CONST.道具_MP = 28;
CONST.道具_幸运 = 29;
CONST.道具_魅力 = 31;
CONST.道具_属性一 = 32;
CONST.道具_属性二 = 33;
CONST.道具_属性一值 = 34;
CONST.道具_属性二值 = 35;
CONST.道具_耐力 = 36;
CONST.道具_灵巧 = 37;
CONST.道具_智力 = 38;
CONST.道具_毒抗 = 39;
CONST.道具_睡抗 = 40;
CONST.道具_石抗 = 41;
CONST.道具_醉抗 = 42;
CONST.道具_乱抗 = 43;
CONST.道具_忘抗 = 44;
CONST.道具_特殊类型 = 45;
CONST.道具_子参一 = 46;
CONST.道具_子参二 = 47;
CONST.道具_宝石武 = 48;
CONST.道具_宝石防 = 49;
CONST.道具_登出消失 = 52;
CONST.道具_丢地消失 = 53;
CONST.道具_宠邮 = 54;
CONST.道具_魔抗 = 55;
CONST.道具_可出售 = 56;
CONST.道具_已鉴定 = 63;
CONST.道具_耐久 = 65;
CONST.道具_TIMELIMIT = 68;
CONST.道具_ENDTIME = 69;
CONST.道具_VAR1 = 70;
CONST.道具_VAR2 = 71;
CONST.道具_VAR3 = 72;
CONST.道具_VAR4 = 73;
CONST.道具_魔攻 = 74;
CONST.道具_宠帮ID = 77;
CONST.道具_重量 = 78;
CONST.道具_所有者 = 186;
CONST.道具_鉴前名 = 4000;
CONST.道具_未鉴定名 = 4000;
CONST.道具_已鉴定名 = 4001;
CONST.道具_名字 = 4001;
CONST.道具_刻印 = 4002;
CONST.道具_自用参数 = 4003;
CONST.道具_刻印玩家 = 4004;
CONST.道具_FIRSTFUNCTION = 4005;
CONST.道具_INITFUNC = 4005;
CONST.道具_WATCHFUNC = 4006;
CONST.道具_USEFUNC = 4007;
CONST.道具_ATTACHFUNC = 4008;
CONST.道具_DETACHFUNC = 4009;
CONST.道具_DROPFUNC = 4010;
CONST.道具_PREPICKUPFUNC = 4011;
CONST.道具_PICKUPFUNC = 4012;
CONST.道具_LASTFUNCTION = 4013;
CONST.道具_Obj索引 = 6000;
CONST.道具_已装备 = 6002;

--[[
战斗信息属性，用于Battle.GetEntryData
]]
CONST.BATTLE_ENTRY_BID = 2;
CONST.BATTLE_ENTRY_SIDE = 3;
CONST.BATTLE_ENTRY_ESCAPE = 4;
CONST.BATTLE_ENTRY_FLG = 5;
CONST.BATTLE_ENTRY_POSITION = 6;
CONST.BATTLE_ENTRY_RECOVERY = 7;
CONST.BATTLE_ENTRY_AMNESIA = 8;
CONST.BATTLE_ENTRY_MAGICDAMAGE = 9;
CONST.BATTLE_ENTRY_GUARDIAN = 10;
CONST.BATTLE_ENTRY_DUELPOINT = 11;
CONST.BATTLE_ENTRY_GETPET = 12;
CONST.BATTLE_ENTRY_SKILLEXP1 = 13;
CONST.BATTLE_ENTRY_SKILLEXP2 = 14;
CONST.BATTLE_ENTRY_SKILLEXP3 = 15;
CONST.BATTLE_ENTRY_SKILLEXP4 = 16;
CONST.BATTLE_ENTRY_SKILLEXP5 = 17;
CONST.BATTLE_ENTRY_SKILLEXP6 = 18;
CONST.BATTLE_ENTRY_SKILLEXP7 = 19;
CONST.BATTLE_ENTRY_SKILLEXP8 = 20;
CONST.BATTLE_ENTRY_SKILLEXP9 = 21;
CONST.BATTLE_ENTRY_SKILLEXP10 = 22;
CONST.BATTLE_ENTRY_SKILLEXP11 = 23;
CONST.BATTLE_ENTRY_SKILLEXP12 = 24;
CONST.BATTLE_ENTRY_SKILLEXP13 = 25;
CONST.BATTLE_ENTRY_SKILLEXP14 = 26;
CONST.BATTLE_ENTRY_SKILLEXP15 = 27;
CONST.BATTLE_ENTRY_SKILLLEVELUP1 = 43;
CONST.BATTLE_ENTRY_SKILLLEVELUP2 = 44;
CONST.BATTLE_ENTRY_SKILLLEVELUP3 = 45;
CONST.BATTLE_ENTRY_SKILLLEVELUP4 = 46;
CONST.BATTLE_ENTRY_SKILLLEVELUP5 = 47;
CONST.BATTLE_ENTRY_SKILLLEVELUP6 = 48;
CONST.BATTLE_ENTRY_SKILLLEVELUP7 = 49;
CONST.BATTLE_ENTRY_SKILLLEVELUP8 = 50;
CONST.BATTLE_ENTRY_SKILLLEVELUP9 = 51;
CONST.BATTLE_ENTRY_SKILLLEVELUP10 = 52;
CONST.BATTLE_ENTRY_SKILLLEVELUP11 = 53;
CONST.BATTLE_ENTRY_SKILLLEVELUP12 = 54;
CONST.BATTLE_ENTRY_SKILLLEVELUP13 = 55;
CONST.BATTLE_ENTRY_SKILLLEVELUP14 = 56;
CONST.BATTLE_ENTRY_SKILLLEVELUP15 = 57;
CONST.BATTLE_ENTRY_HIT = 73;
CONST.BATTLE_ENTRY_DANCETURN = 74;
CONST.BATTLE_ENTRY_DAMAGEUP1 = 75;
CONST.BATTLE_ENTRY_DAMAGEUP2 = 76;
CONST.BATTLE_ENTRY_PARAMETERUPDOWN1 = 77;
CONST.BATTLE_ENTRY_PARAMETERUPDOWN2 = 78;
CONST.BATTLE_ENTRY_WAITTURN = 79;
CONST.BATTLE_ENTRY_GETITEM1 = 85;
CONST.BATTLE_ENTRY_GETITEM2 = 86;
CONST.BATTLE_ENTRY_GETITEM3 = 87;

--[[
对象的动作类型 用于 NLG.SetAction
]]
CONST.CHAR_ACTSTAND = 0;
CONST.CHAR_ACTWALK = 1;
CONST.CHAR_ACTBEGINRUN = 2;
CONST.CHAR_ACTRUNNING = 3;
CONST.CHAR_ACTENDRUN = 4;
CONST.CHAR_ACTATTACK = 5;
CONST.CHAR_ACTMAGIC = 6;
CONST.CHAR_ACTTHROW = 7;
CONST.CHAR_ACTDAMAGE = 8;
CONST.CHAR_ACTGUARD = 9;
CONST.CHAR_ACTDOWN = 10;
CONST.CHAR_ACTSIT = 11;
CONST.CHAR_ACTHAND = 12;
CONST.CHAR_ACTPLEASURE = 13;
CONST.CHAR_ACTANGRY = 14;
CONST.CHAR_ACTSAD = 15;
CONST.CHAR_ACTNOD = 16;
CONST.CHAR_ACTGUU = 17;
CONST.CHAR_ACTCHOKI = 18;
CONST.CHAR_ACTPAA = 19;
CONST.CHAR_ACTACTIONWALK = 30;
CONST.CHAR_ACTACTIONSTAND = 31;
CONST.CHAR_ACTBATTLE = 40;
CONST.CHAR_ACTLEADER = 41;
CONST.CHAR_ACTBATTLEWATCH = 42;
CONST.CHAR_ACTPOPUPNAME = 43;
CONST.CHAR_ACTBATTLEDUEL = 44;
CONST.CHAR_ACTINJURY = 45;
CONST.CHAR_ACTSKILL = 46;
CONST.CHAR_ACTLEVELUP = 47;
CONST.CHAR_ACTPETINJURY = 48;
CONST.CHAR_ACTPETLEVELUP = 49;
CONST.CHAR_ACTTURN = 50;
CONST.CHAR_ACTWARP = 51;
CONST.CHAR_ACTPICKUP = 52;
CONST.CHAR_ACTDROP = 53;
CONST.CHAR_ACTGRAPH = 60;
CONST.CHAR_ACTRIDE = 70;
CONST.CHAR_ACTVEHICLE_RETURN = 80;
CONST.CHAR_ACTVEHICLE_DEPARTURE = 81;
CONST.CHAR_ACTVEHICLE_ARRIVAL = 82;
CONST.CHAR_ACTSTALL = 200;

--[[
JOBS 用于 Data.GetJobData
]]
CONST.JOBS_ID = 0;
CONST.JOBS_ANCESTRY_ID = 0;
CONST.JOBS_WHICHASSORT = 1;
CONST.JOBS_ANCESTRY_JOBSID1 = 1;
CONST.JOBS_COST = 2;
CONST.JOBS_ANCESTRY_JOBSID2 = 2;
CONST.JOBS_REQUIREFAME = 3;
CONST.JOBS_ANCESTRY_JOBSID3 = 3;
CONST.JOBS_REQUIRESKILL1 = 4;
CONST.JOBS_ANCESTRY_JOBSID4 = 4;
CONST.JOBS_REQUIRESKILL2 = 5;
CONST.JOBS_ANCESTRY_JOBSID5 = 5;
CONST.JOBS_REQUIRESKILL3 = 6;
CONST.JOBS_ANCESTRY_JOBSID6 = 6;
CONST.JOBS_REQUIRESKILL4 = 7;
CONST.JOBS_ANCESTRY_JOBSID7 = 7;
CONST.JOBS_ANCESTRY_JOBSEND = 7;
CONST.JOBS_REQUIRESKILL5 = 8;
CONST.JOBS_ANCESTRY_RATE1 = 8;
CONST.JOBS_ANCESTRY_RATE2 = 9;
CONST.JOBS_ANCESTRY_RATE3 = 10;
CONST.JOBS_ANCESTRY_RATE4 = 11;
CONST.JOBS_ANCESTRY_RATE5 = 12;
CONST.JOBS_ANCESTRY_RATE6 = 13;
CONST.JOBS_ANCESTRY_RATE7 = 14;
CONST.JOBS_ANCESTRY_FAMELIMIT = 15;
CONST.JOBS_NAME = 4000;
CONST.JOBS_ANCESTRY_NAME = 4000;
CONST.JOBS_SYSTEMNAME = 4001;

--[[
OBJTYPE 用于 Obj.GetType
]]
CONST.物件_没 = 0;
CONST.物件_人 = 1;
CONST.物件_道 = 2;
CONST.物件_币 = 3;
CONST.物件_传 = 4;
CONST.物件_船 = 5;
CONST.物件_码头 = 6;

CONST.按钮_无 = 0;
CONST.按钮_确认 = 1;
CONST.按钮_确定 = 1;
CONST.按钮_关闭 = 2;
CONST.按钮_确定关闭 = 3;
CONST.按钮_是 = 4;
CONST.按钮_否 = 8;
CONST.按钮_是否 = 12;
CONST.按钮_上一页 = 16;
CONST.按钮_上取消 = 18;
CONST.按钮_下一页 = 32;
CONST.按钮_下取消 = 34;
CONST.按钮_上下取消 = 50;

--[[
宠物属性 用于 Char.GetData
]]
CONST.宠物_主人RegistNumber = 51;
CONST.宠物_捕捉难度 = 53;
CONST.宠物_基础忠诚 = 54;
CONST.宠物_技能栏 = 55;
CONST.宠物_获取时等级 = 56;
CONST.宠物_PETID = 72;
CONST.宠物_忠诚 = 560;
CONST.宠物_Weight = 584;
CONST.宠物_MaxWeight = 585;

--[[
宠物战斗状态 用于 Char.SetPetDepartureState
]]
CONST.宠物状态_无 = 0;
CONST.宠物状态_待命 = 1;
CONST.宠物状态_战斗 = 2;
CONST.宠物状态_休息 = 3;
CONST.宠物状态_散步 = 16;

--[[
对象类型 用于 CONST.对象_类型
]]
CONST.对象类型_无 = 0;
CONST.对象类型_全部 = 0;
CONST.对象类型_人 = 1;
CONST.对象类型_怪 = 2;
CONST.对象类型_宠 = 3;
CONST.对象类型_NPC = 80;

--[[
玩家装备的道具栏位置
]]
CONST.位置_头 = 0;
CONST.位置_身 = 1;
CONST.位置_左手 = 2;
CONST.位置_右手 = 3;
CONST.位置_腿 = 4;
CONST.位置_首饰1 = 5;
CONST.位置_首饰2 = 6;
CONST.位置_水晶 = 7;

--[[
玩家组队模式
]]
CONST.组队模式_无 = 0;
CONST.组队模式_队长 = 1;
CONST.组队模式_队员 = 2;
CONST.组队模式_宠物 = 3;

--[[
地图类型 用于 CONST.对象_地图类型
]]
CONST.地图类型_普通 = 0;
CONST.地图类型_迷宫 = 1;
CONST.地图类型_家族 = 2;
CONST.地图类型_房屋 = 3;
CONST.地图类型_LUAMAP = 5;

--[[
对象种族
]]
CONST.种族_人型 = 0;
CONST.种族_龙 = 1;
CONST.种族_不死 = 2;
CONST.种族_飞行 = 3;
CONST.种族_昆虫 = 4;
CONST.种族_植物 = 5;
CONST.种族_野兽 = 6;
CONST.种族_特殊 = 7;
CONST.种族_金属 = 8;
CONST.种族_邪魔 = 9;
CONST.种族_神族 = 10;
CONST.种族_精灵 = 11;

--[[
属性常量
]]
CONST.属性_地 = 0;
CONST.属性_水 = 1;
CONST.属性_火 = 2;
CONST.属性_风 = 3;

CONST.DUNGEON_CLR_1 = 251;
CONST.DUNGEON_CLR_2 = 252;
CONST.DUNGEON_CLR_3 = 253;

CONST.FEVER_RESETTIME = 258;

--[[
怪物基础属性 用于Data.EnemyBaseGetData
]]
CONST.EnemyBase_编号 = 0;
CONST.EnemyBase_BP = 1;
CONST.EnemyBase_浮动 = 2;
CONST.EnemyBase_种族 = 3;
CONST.EnemyBase_体力 = 4;
CONST.EnemyBase_力量 = 5;
CONST.EnemyBase_强度 = 6;
CONST.EnemyBase_速度 = 7;
CONST.EnemyBase_魔法 = 8;
CONST.EnemyBase_捕捉难度 = 9;
CONST.EnemyBase_图鉴等级 = 10;
CONST.EnemyBase_魅力要求 = 11;
CONST.EnemyBase_命中 = 12;
CONST.EnemyBase_必杀 = 13;
CONST.EnemyBase_地属性 = 14;
CONST.EnemyBase_水属性 = 15;
CONST.EnemyBase_火属性 = 16;
CONST.EnemyBase_风属性 = 17;
CONST.EnemyBase_抗毒 = 18;
CONST.EnemyBase_抗醉 = 19;
CONST.EnemyBase_抗睡 = 20;
CONST.EnemyBase_抗混乱 = 21;
CONST.EnemyBase_抗石化 = 22;
CONST.EnemyBase_抗遗忘 = 23;
CONST.EnemyBase_图鉴等级2 = 24;
CONST.EnemyBase_闪躲 = 26;
CONST.EnemyBase_反击 = 27;
CONST.EnemyBase_技能栏 = 28;
CONST.EnemyBase_形象 = 29;
CONST.EnemyBase_MODEXP = 30;
CONST.EnemyBase_图鉴编号 = 32;
CONST.EnemyBase_能否捕捉 = 34;
CONST.EnemyBase_出生技能1 = 35;
CONST.EnemyBase_出生技能2 = 36;
CONST.EnemyBase_出生技能3 = 37;
CONST.EnemyBase_出生技能4 = 38;
CONST.EnemyBase_出生技能5 = 39;
CONST.EnemyBase_出生技能6 = 40;
CONST.EnemyBase_出生技能7 = 41;
CONST.EnemyBase_出生技能8 = 42;
CONST.EnemyBase_出生技能9 = 43;
CONST.EnemyBase_出生技能10 = 44;
CONST.EnemyBase_名字 = 4000;

--[[
Enemy 用于 Data.EnemyGetData
]]
CONST.Enemy_编号 = 0;
CONST.Enemy_Base编号 = 1;
CONST.Enemy_最低等级 = 2;
CONST.Enemy_最高等级 = 3;
CONST.Enemy_最低数量 = 4;
CONST.Enemy_最高数量 = 5;
CONST.Enemy_AI = 6;
CONST.Enemy_战斗经验 = 7;
CONST.Enemy_战绩 = 8;
CONST.Enemy_攻击模式 = 9;
CONST.Enemy_可否捕捉 = 10;
CONST.Enemy_掉落物品1 = 11;
CONST.Enemy_掉落物品2 = 12;
CONST.Enemy_掉落物品3 = 13;
CONST.Enemy_掉落物品4 = 14;
CONST.Enemy_掉落物品5 = 15;
CONST.Enemy_掉落物品6 = 16;
CONST.Enemy_掉落物品7 = 17;
CONST.Enemy_掉落物品8 = 18;
CONST.Enemy_掉落物品9 = 19;
CONST.Enemy_掉落物品10 = 20;
CONST.Enemy_掉落几率1 = 21;
CONST.Enemy_掉落几率2 = 22;
CONST.Enemy_掉落几率3 = 23;
CONST.Enemy_掉落几率4 = 24;
CONST.Enemy_掉落几率5 = 25;
CONST.Enemy_掉落几率6 = 26;
CONST.Enemy_掉落几率7 = 27;
CONST.Enemy_掉落几率8 = 28;
CONST.Enemy_掉落几率9 = 29;
CONST.Enemy_掉落几率10 = 30;
CONST.Enemy_偷窃物品1 = 31;
CONST.Enemy_偷窃物品2 = 32;
CONST.Enemy_偷窃物品3 = 33;
CONST.Enemy_偷窃物品4 = 34;
CONST.Enemy_偷窃物品5 = 35;
CONST.Enemy_偷窃几率1 = 36;
CONST.Enemy_偷窃几率2 = 37;
CONST.Enemy_偷窃几率3 = 38;
CONST.Enemy_偷窃几率4 = 39;
CONST.Enemy_偷窃几率5 = 40;
CONST.Enemy_是否二动 = 41;
CONST.Enemy_是否BOSS = 42;
CONST.Enemy_召唤Enemy1 = 43;
CONST.Enemy_召唤Enemy2 = 44;
CONST.Enemy_Talk编号 = 45;
CONST.Enemy_名字 = 4000;
CONST.Enemy_战术 = 4001;
